name: Terraform Plan
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
jobs:
  plan:
    strategy:
      # prevent all jobs from being cancelled if one fails
      fail-fast: false
    name: Plan opsisdead
    runs-on: ubuntu-latest
    steps:
      - name: Plan
        uses: catalystsquad/action-terraform@v1
        with:
          command: plan
          work-dir: terraform/site
          provider: aws
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
